[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "b4dcedc8ef2a0136edfa5e50a7b205e22b8f07ac"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "67de7a6d412e4e56a102ee83aeb3d6af13b462dca8b2f09969dd94b216a8677f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-x86_64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "24c429bc2cabd57210e63b1b669e22350ce31da7"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "47862ead4ad8c8a046fe017580b4dfc5ab0abe1da0b27cd595acbf90f1748cd9"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-i686-linux-gnu.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "62d16a6625efd1b4e6a4554fa05fb0a077253220"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2015b4cdca65b61afd78b010f006b676158feacc33b6d701a012135f2ae533a7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-aarch64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "880285e882563e74001749cae85ac922ce6c4c4a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ae83c2018a3ff9ef349978c8b29c194637188e446f14f403ba212ea4b1aa4b3f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
git-tree-sha1 = "7406f70ff3a53b8c582aedd8b9035584172544a8"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c20d4f4d2ac630404b8c7a1f1d3fd6b3f3a8c242c3baf3d1a325bf522c4245e2"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-powerpc64le-linux-gnu.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "c09e266bb3964e5b53fa52643bba6e54689e2e59"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ff33c43b1b42ffe688a0e10887d81d02a2e40656dc70a2841c263626bf427eb2"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-x86_64-linux-musl.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "a93e0c608dfe3dd7ebffbe102bbf6085f39e476a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2f7956baf08a5b22ec31e1fb25312b44596a1437137610d9c4a5fad9f2e15bb0"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-i686-linux-musl.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "a4c679bf022fb2cd9f722db7c9bddbaa5597f3a6"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "62d071fd6aab6eef59778c99445783ea7fcbc4049a9ff25081cf138e1b47800f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-aarch64-linux-musl.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2c2a5ea588247b33b59cfdc54c4b1059ded84e9c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a5bd52167a97cc91d0a2c44bcd4d6c2947efaab22d1a94ff9f97cd3b8695cf53"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-armv6l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab08bb23b1897d9d628fe239391af8f1d9b0c8a2"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "066186cee6a1ff510e421d21314643259bdb1983ee55b930c40cd2091344a749"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-armv7l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "388490b93bc5f9453c55a61b81f90884ca1aa040"
os = "windows"

    [[libLLVM.download]]
    sha256 = "345e8d335bd6b7d2967222e4ceb3b593405952dffdb8a7edd5016e522a45dc01"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-x86_64-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "ddd8e20f9e981005e1fb5dc323b79cf475ea5a56"
os = "windows"

    [[libLLVM.download]]
    sha256 = "0372b332ea0e4269f16557818b8b2362e15042401360dbe09ef2bd29198383aa"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-i686-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "d968b75502df50e65a291fe1d54681c0910fdef9"
os = "macos"
os_version = "14"

    [[libLLVM.download]]
    sha256 = "b4d8e0b94b08297f451d938ab6d6b18616ec507790c0767d21fbf9d1e3e3aef1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-x86_64-apple-darwin14.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "e224da3342a07a129f82505c191844263cba10f2"
os = "macos"
os_version = "20"

    [[libLLVM.download]]
    sha256 = "6f42f9f771b961bd7e3959cb61e0f2912c5c49766befb1cc41ab1cec36078bf3"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-aarch64-apple-darwin20.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "7511429b3d764d946a4e0c5f4668e644f8e5e097"
os = "freebsd"
os_version = "14.1"

    [[libLLVM.download]]
    sha256 = "73a4ea31947561030793f40a684541142b14e92bbf1e30f1584cf3876120bfa4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-x86_64-unknown-freebsd14.1.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "a431065dff8b0a8d8d9b1bbc5791eb8557447f91"
os = "freebsd"
os_version = "14.1"

    [[libLLVM.download]]
    sha256 = "f06c6285bcef05f4b092ec2866b33f1a155c465b3d74d1c327632789fe3809b4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.8-aarch64-unknown-freebsd14.1.tar.gz"

[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "5c5492cfc16a199e1e6d3e6d5f4bc1d4717fffd8"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "a0c7a1c1698b9467ae5ec8d063ee21c4285af109e417cc21d30727ea856f98aa"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-x86_64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "1c9aefe1bfddd3f85888fa075f72bff91c3a210a"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "349bb5fd7d79a2c767197ad12e82ce6241c5e2b8dab04d45cfe0b1c88999ce7f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-i686-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "b03e5ae763a8a1c1ce3cee526f7bee8e02485820"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "5eace0bb4a0a239ac7db60c5b9c03aceaf3f5a3a3d9e3b057bcff56b4212f645"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-aarch64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53a0baca58491e66aa814e752a1d6587cb1298b1"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "6ef91e5de04403ce55a203c0b96738acae98e6d7af7bd66a9e44f2654e9a9949"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "32c05217d2cefb02a3b9fc49550d90cf1f399ee1"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "24ccb336b4f4f74fb78ec37486e07261ff5bad1ff5b1d998ca6c489da22bbc7f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "07d54910fcb78d5229fd7fbb1e5ca977cf4ce658"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "061d7dc91f04aea2ac94cacbcd940ebfa29a7ad3edf36159fbc36fbcbfdf9bc1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-x86_64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "bafa0602a1d16f94265ea34d20fb00ae2b429e82"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "5e9a642a3e029390f16d097d7106bde5f16f36194e67410463901295259104f2"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-i686-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "8814b0e139ba497ccb37fb109b37140653d52623"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "d275537e26fc3cae205aa69a90993322d2992e16b046c1b088d35d3cc626fd00"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-aarch64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "664eb88a7d04bf8da8d44a7af8f6f2e07fa91cfd"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "94d52caeb191c35eaf8d08bbc0aac47dee3f16f1a7b1d2f55ac3e03dca457754"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "155e6cdc534df9ec2a3cf6ba1a38b0d121abb25d"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "d44c58f9b3a360a86370049ed47fa6ffa1a85a7ab37883804c6d4d583f7288e4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "2656a26d37330be13985abab50800a571dfa222c"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "9554bab3716835c4040cdb6a9bff3b7956ab45aa53a71c68a2a3ae0fd0e617a1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-x86_64-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "b72673bb028695ec18ff2007588e3aa7dfe6d06a"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "7d63712632a0f03913409cad1f83e5be98964a045324724768322a943ab81e6d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-i686-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "c8f3a6dafbb2a05c819294c62160fdb70bc74849"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-build_log.download]]
    sha256 = "0bd820f400f5e1d96ca57fd6d419825800df4b23ac9adbcb71008d694b95341a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-x86_64-apple-darwin14.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "1e9ef98caaebd9306c3727c1d5a7c6220e92f3e4"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-build_log.download]]
    sha256 = "de4e81668095aa64f2667e33c9a4c938a6ef0f25d3ab126093d2019b19d2407d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-aarch64-apple-darwin20.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "6fcd65a746af635eab090f73b17733aef15dcabb"
lazy = true
os = "freebsd"
os_version = "14.1"

    [[libLLVM-build_log.download]]
    sha256 = "66764fb0df8c113fa7f5d8056012cef5a8d5297f66a0d0ab5c80b82089d58efd"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-x86_64-unknown-freebsd14.1.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "71b5f00b6b93145e2b13bb8790e5c52cc44738fc"
lazy = true
os = "freebsd"
os_version = "14.1"

    [[libLLVM-build_log.download]]
    sha256 = "dfa3c8f50d04a6cde3f4714fee71eb4862e81b8991c9132e38932b3a4b756397"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.8-aarch64-unknown-freebsd14.1.tar.gz"

[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "88ee7eb9d1ef53eed9bdc3eebee17a5bbe989cf2"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "2db57def040095c18073664f3e7e917cabe1dd4a87831b4718b50abaf1bdd667"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-x86_64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "abf3deb855425abec46099a8fbf2cce25f88ea63"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "f8e78df1aa3abb17f5f83ee64e79ce8354c5ae58026a334c3ee4c82ef41b0329"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-i686-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "d15802fbdf557cbc49ab865959b16183bd696351"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "b43c2541ac56d7674cf0225eceeeb76c48a0b780e24d5f369a5f18c2fe22c92f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-aarch64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "30e8a8a571c644ae7353612a296f0c7530c269d4"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "5ec57ea22ca93bda97c45682304d9c6b4c0d432b6a4de9252b0749e08f98be11"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "5aca9176a1f88f9ab75c7cf5b497a43e3a92dc51"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "a122dbac2f1a0b5fceb4dbc10d6a1583bdf5d0bd5b5be03f43a22dd575731f7b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2e805efb63e01a63be1727652ea2f4589d467e11"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "c382f2fc4a83268ca568ac68813dcde755d7006be805202b6f3b01fe53d1a9c5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-x86_64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "7a6ac7e5f3d8a11fedcd43b4be845427dca66e21"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "82c362cbc04562ea87717130b64e43cc525d36ae6e62b7451ad3bacc7b5dab96"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-i686-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f645c33d8d29cc676cd46b4e138f798b81ff9bd4"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "2802fc1350905bacfa20a7999f53fb96f646def9c97ef9b98416376caabfcb00"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-aarch64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b671e2945512ee6192f78fb9e882c95d26f2141e"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "e49cf2d8c3f22bf5ae46bd96dbb177ab15329daa861ac7265dacaa6f3208b110"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "262d5377ddc474526cb5895759768ee74e18a501"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "1d5afa642abcf3dbf4c60225dc35cc1ce7b0f406b97bab36730ea3f8b7ab0e7c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "afc8860e044124065dc4b3457344bda9f8d4d656"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "7cb93fb861f97850d0717d8d2314873a22b7d3ab3d66fce5a9947f28102e17a1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-x86_64-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "b6ee00b7cbcac5cadd936c0dc5636412446ac93e"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "2b3d3d9728a68368c0c5ae7cf249791f5b1f0c64d7aa86d9c00526ab9d0802c8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-i686-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1c22e568f7e52ba918fc0566c379a499cb54ac53"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-extract_log.download]]
    sha256 = "45033a138d97bb388c74f0429230a41f64610db6bbf6af0957ed5c85c685c4da"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-x86_64-apple-darwin14.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "1c24accd2d2a893fd3e446be13171be3127b2860"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-extract_log.download]]
    sha256 = "d14bd4cccb198f6ba24558ff3657b75b48633514ee8e001e5b84520e03790afd"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-aarch64-apple-darwin20.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "183c32b67b33fe91209927ad2df2ac399adba901"
lazy = true
os = "freebsd"
os_version = "14.1"

    [[libLLVM-extract_log.download]]
    sha256 = "3af8ef68daf781b66c4846909db58cf5529d8c6b0def7e186c88da8a359ca072"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-x86_64-unknown-freebsd14.1.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "1637f8b79b5aa5435d1638c273e7c83972b9a90f"
lazy = true
os = "freebsd"
os_version = "14.1"

    [[libLLVM-extract_log.download]]
    sha256 = "7a9ee250088c274c0c63708119cd0861280e357b98afa4b115cb334e97e773b3"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.8-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.8-aarch64-unknown-freebsd14.1.tar.gz"
