[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "552c249f9016daf7274905631514b3df41454684"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e1f0e9478fe691c21b8bda3f0bc339ef4dc299c406a26f3f067aad5f64722dc6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "5cc8e00997b8aecb730f8c7b40f8d317ac479913"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0915ffd4bd92b7c88e57ee88019594a73c05e46edeb3316e0bfd1b29ff9d4f08"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "b874144d398402f53ff66b5eb5dd21f97015541d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e6a5c8f277f4cf218ffe3702105f7314fa1b8bc0fe382d44096e9370122b82b7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da21c10406df38f52917935b788854a17d170fb3"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "192b9278f9dddef983007f3104565617309954e5e10c7fdff995e6073975c073"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
git-tree-sha1 = "a4831f2e5ea0e3f4668213f06491890501ef196f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "acb2156f6d37f0d6f9125055c243096ebcecbad93d79c4bbc6c27d4a7520f312"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "61f44ab16c1b10a75e6b8d471c4bb3482d8e8f5c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "43d8cf57cc7cb92978ba10233b035079f06c09f1c7cac69924aa1853093b5c29"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "88e1cb2547cf83d490c1082f3d9d1363eca66963"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2b40035edb001bc4daa22704580c90bfc98aaaa223b9f5ed74d6e6cbdea4cf97"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "500be08e7c71b9b5cd760f74c232622f2e13d258"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "45100c02345d8bfebb8535f4f861d0d61461527c7a5f98688aeef1a156af1ec4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8bc09706e5cd660b13a71f873b051b5b95662ed4"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5677d1180f2992a2a27773874b01b34ec3ea045463d98cca1bee3594dd88e81e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3829ed8dbfd32fa1653b7f364ddfdcefcd2029d5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9b6e45540c611026fcaced2465a93edc7e55b40c19cc04378262c95eea5f6b81"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "388490b93bc5f9453c55a61b81f90884ca1aa040"
os = "windows"

    [[libLLVM.download]]
    sha256 = "03be6f7d0a6c4f733b5f40b827449054721ce4fdf11dc7c51123935e87d10c96"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "ddd8e20f9e981005e1fb5dc323b79cf475ea5a56"
os = "windows"

    [[libLLVM.download]]
    sha256 = "5e0e35bc1f71f0727c10d5438c35436d74d4e2fc9282bd97d2bf13032ed6d4bc"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "d968b75502df50e65a291fe1d54681c0910fdef9"
os = "macos"
os_version = "14"

    [[libLLVM.download]]
    sha256 = "e9f260411bea8cc6962f84e8f55587efe8a91b95d12a7937a4c3f005d0161eb5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "e224da3342a07a129f82505c191844263cba10f2"
os = "macos"
os_version = "20"

    [[libLLVM.download]]
    sha256 = "eec6f622cd82107e135b921ad6253f829416e30ca16fb328c526e60808864867"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-apple-darwin20.tar.gz"

[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "dc1c95ef386f75022f88dfdc655c01463c43e35f"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "f86a036094620644ee0e4b5b805602023a7fe1d25bea5e97afa323bbf37a7776"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "67fa6289bae75d2e6e07b56ca171f8a8f1b529fd"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "dcfae33026d162fa447d562548f2538a556ddaacf7d5ae5396600533ea628d3c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "1484bcafe1ce2238bc1543774d736638d950ae1b"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "94a2279af3245dbbb9e17cc92c38658579e13e518db04724594607ca5173a69b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b950ce6f9c78d80d4d7e07562914cc39fbcd85d"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "25be772d80e6aaf1cf47c18106a1b34f78043a75d99d3732712e035b2ee31e10"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "46079d3056895ddac0aebcd55f3304b39d4fc0b3"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "59fd97c5947548c0a8f5f32a397195aef4ba19b956cdb3225841aba4e85af65e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "89afec92cfbda02d971ebcfd95dd32894371864b"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "25258951c99c0a64598930b3072b388ffd516d945e224533e6600df608a280d1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "b26db272a217143174ef320c8e4928ebcdee7bbc"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "d075afb70a8a975e514c17d0e75919e5ac7d07d8c3d73ae113fc5232bcc309ba"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "6e7689d2d6896b9cc166f7243b607f1887970415"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "619666102051332cb526ccfd3da33ec17b6b18193ac91667000d6129146686b5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "895d5af43f642dafe85ac6dd5df5d5a9d78ce45f"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "85df5b1c4c5b891c3750b72337c93d3961f0e97ab49778d1fd9850a9d05ab245"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "69adce2d8800bc3f10ef3c9447df3982e34832ea"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "ea834ee32e7582910aa88c68fedce2f1485b1e8eb9df6731a285edf446dcc312"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "58f7ce9b27b07410d56099eb30b9255b49baf0b8"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "857ccd09e3e34d24515a6bcaf00f4d61f5f9db26ffdac9c2144913cce938fb2b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "4db3a07fa3875d4b542e6da33ad71f39c7a9030c"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "b81c0c770084c9fda5740c876616e35b37a9bed0028064cb6912b8a796ec5df4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "d9bcf9059383a8d7e81f470c0306388663a39796"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-build_log.download]]
    sha256 = "476d09309cc3c3fcd2cb057a35527d0c464ba84ef47a003687746d3210911bb6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "44a8de0f10d2c759f0e72b04dec8d73b4cd1b094"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-build_log.download]]
    sha256 = "2c9e4658121affb1c79e6126b0c9aae4a37e693b1f2dec0b15c15924a0b43081"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-apple-darwin20.tar.gz"

[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b7d496e4356ebef79cbb75275c63328ae7e0019c"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "c0af0a62ef944e7c99f836237a88842233fe035c6fb4cc63224c94101a0cdcaf"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "bee7ff74a802f5c49f08d7ad42022081b970a091"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "da48055024ec7b9e9ed64e6414f074f0e3da0669d649c8f3c20787dfb6ecba10"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "dc7d1ac5c97b6efdfec4cb838b8a40690c0fd30f"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "19cded1daf310abf3ce437088e686909d632f280979cf190b7cbe58b75001f61"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80388686f367bd2f9263ae9e00d95d53300d4989"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "6361dfaaee8f00c6c312d787a22b3fb66e77fd6019c89166cb33c122c60fd27f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "8e1009dae949758ffb6ab1dee298ecb198e348f3"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "2cb0661b1eb144f17360727787994b08953cbcc0b1a5f6e28165a5b65d97df7d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "0aed83fde39544bc9d580f4e075c59cb4b6facdc"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "206d54e7e319e8605e4ea41e3f5e8e7e1cc6fafbf128ccd57609df8b99c0a3a4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "4f8f6686637baa76a715c7fba637e18723627ec7"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "40bf0844900f139614918c083ad3da23f5e4d7e60d88e2ab8b1ffb3b08193da8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5c97c7993b9e7df29bb7a2d9623a23e99b89fd01"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "e716f8dcaa736e30ccb3ddaf298738748ce86617062973d939eba63b5ae3a826"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21aeb7a3fa21da0373efd8bffacd6f45c6b54d1e"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "62a4ad339606dfe494410d400230cc94f3294c77308200b7d073ba23fb1c85ed"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8559cf48dc8afc4f9e8905097f09b092f696b577"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "166f1306c51b6ca0ad480ea6a2562813ef7bfd0dbefe1e1ea215a463cb9f12d1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d7023614f5fa3efdca57a4d533dc35f8328041c1"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "3aa81055cb799feeb95ead11b27c1655eb5a44c3b01daaa5b4d87d491c16488e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "336259bd1eb12765649c44a4b0797993947c230f"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "75ee1b5cadcec2c584e65eeb121776a17e7e643ef1e368758ef0dd311a52c84f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1f1e01abdd90cc5a48d0613ad0246c773d872481"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-extract_log.download]]
    sha256 = "9f6ce96eb6529e8cf216fb770d3d246a37e3166e2c0aabcd13f6b0a623b3e1cc"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "58b9996e2f3d0e1046279ef7a05f011a90994966"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-extract_log.download]]
    sha256 = "75b9e8dbf1c22068020cd1343f98a5223f9738940ef5a4c8dc58f96d5bf8b6f5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-apple-darwin20.tar.gz"
