[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "b4dcedc8ef2a0136edfa5e50a7b205e22b8f07ac"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "281b90dd08e74018dcaa1d318aab18218a1ce6af7f6b2f1742250f29ba76ec2c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "24c429bc2cabd57210e63b1b669e22350ce31da7"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4156f8dca2a3d5ccac268ed63ed2ce5678067d98a4d7ae73ed7e5299ddbf3061"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "62d16a6625efd1b4e6a4554fa05fb0a077253220"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0582b9ee34a978415fdc862c39dd8a61a713d4a5e48c6161483fa19264eb5c33"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "880285e882563e74001749cae85ac922ce6c4c4a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ff9eba016541cb12e1f184f69393e54b3a04ec9998446fb8495f59bc971ef533"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
git-tree-sha1 = "7406f70ff3a53b8c582aedd8b9035584172544a8"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "21c870563d5f344766661b2d34e49d2263207affaf37fb15b89d489226c8c90a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "c09e266bb3964e5b53fa52643bba6e54689e2e59"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3851241fe3b8064528b85ef57cf6351148ebf10d45fda4de3d6aeba53609d60e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "a93e0c608dfe3dd7ebffbe102bbf6085f39e476a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "32a3ad457ea5b19275c5d0ba1c0fe0d83d88a6212ea18d6e274834da3d98d0d5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "a4c679bf022fb2cd9f722db7c9bddbaa5597f3a6"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a3e2d3b15adbe2af17a2c1bad9a55563c0974a5df3c4be4d488fcaca7a55a9d1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2c2a5ea588247b33b59cfdc54c4b1059ded84e9c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c2349ae8e9ce32ebefbf2f019f93822330045c96c987119ace31208374ba5381"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab08bb23b1897d9d628fe239391af8f1d9b0c8a2"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bc5c6b34a5f699df389924f8d4f40fbce10b04d280616d79999694bf512bf26c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "388490b93bc5f9453c55a61b81f90884ca1aa040"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ce6bae12e0742ef4ac463bf3abca333d060f20d076f79495820b4e667481298d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "ddd8e20f9e981005e1fb5dc323b79cf475ea5a56"
os = "windows"

    [[libLLVM.download]]
    sha256 = "1f80db01f334454a46f848ac7caa55033f1588cd8a1a34b0b1df138e923cbf41"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "95771c5d38e7c7930aed2619176648440c7a6d51"
os = "macos"
os_version = "20.0.0"

    [[libLLVM.download]]
    sha256 = "a2d3594e2a301ab58e23e7b47c3add40378ff193d891ba50e4593d9ea5b37fd1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-x86_64-apple-darwin20.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "f31224986b96965ccb58e04ed9e18d02781d26d7"
os = "macos"
os_version = "20.0.0"

    [[libLLVM.download]]
    sha256 = "d51556dbbc6bd14fe6e9e9c6172b068b289478c8280f04f7026d457a86839d69"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-aarch64-apple-darwin20.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "53aedf30fbb2402c629df39ccac931d2e6849954"
os = "freebsd"
os_version = "14.1.0"

    [[libLLVM.download]]
    sha256 = "7e3899600217e8dac110dbd957adc6f4f38bee61535e8029099748d62c7bf9c9"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-x86_64-unknown-freebsd14.1.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "b97878a20f28993a0773bf5860c78fdb6f6d6ee4"
os = "freebsd"
os_version = "14.1.0"

    [[libLLVM.download]]
    sha256 = "e3017fcf183aa26882e9752e5de691b0e250054b2b4dc46666713ba3c608df6a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-v17.0.7-aarch64-unknown-freebsd14.1.tar.gz"

[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "9569a99a5a0d064cd61d0f8e058cc960ed513c4d"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "a3be7de050c3c7eb66cdb31a481e494ad72f718449f6c15e72b6818eab699b44"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "a7a96f696334991d3f9e6b609e4370df969c4a5e"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "488167f41cb00864361d973a04c4c3132592b0f1af1438fc34cadb5cd37c81dc"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "0709ae5f1006dcfc70fa50951527c09a01f4fcd3"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "f372440189353fd6b0aa346de97f6c995a6b9392fb21e9a91305aa739ae07cbc"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c857b3d0d25acb60a34dcd77941ee1325ab9eb06"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "7a5744cb7dfc327ae7dc00874c9210b46a346d2e46c2cc87f432e4edc7ea55e7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "49a8bb7b6795398e0a51bce67716c7064d4f7c99"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "6e8f6d50460092e071d107d13ee55e1dbcc8c2b69ac0cd1302b74210d82b656d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "0fa44025c003b10b78c4cea2e0319101da128da0"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "5b4b6621c457a7b891c3882dc93ae221689dc85a6ed9a7b3c46d4c67ac48a7d8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "9ed3475f205982c97348f42dc0f9b7c62dc8e768"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "cf35acc9732d90d583821c6c27dd18f72d9ad72d8dab89c5a09ec4ed3271dfef"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "70dd3149e52ebdf65f96f455032a0acddcfed9c2"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "7fc00af55ee4fe572eb64bbf736a5d798e50d6760be0652b7118bd0250c2ac49"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66c6b1318056a9cb90e9526273432c06f8cb5a9a"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "e9a904a81a503365bb6ee79ae0496be5bb3ee2e4e7534137cd6dddbc1cbdc50e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5da148c93733e936904432747a415cc9e3c12f8e"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "6aa0f6dbaf82260757f6071576c32dc558d4f15e387447d6a10fe8fcc29aab56"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "383ef8e43849bba9a8d84e4522438f29e4ff1232"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "650f98b02067eea7585584751d2bd4dd33db7cbd74b74606451b411e2185e3e8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "7bb61d180946f0bde8cc1625b340a5888346df0e"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "63ebb7b7fb4d4c96d41601d8691fe64237e9ede06e1dd5bd9b4114d71c0e4cdb"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "38f6f2bc39f99ad240164aa7949fe9b2b8470639"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[libLLVM-build_log.download]]
    sha256 = "d7d31bb20dfeabf9db2584ce9f4cf47617ea074f1a4ee30a16af229fe2f4ef73"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-x86_64-apple-darwin20.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "04d41f4a23f6dae60fe8eaa5073fdef07183ad25"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[libLLVM-build_log.download]]
    sha256 = "3451c314647aa82875c53226c8aeacf06a1577aecabac2041cc1fe545ef045ad"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-aarch64-apple-darwin20.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "4264e8371f61ebf42690b8d1b8569d7201036f6b"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[libLLVM-build_log.download]]
    sha256 = "37e8ecfa941e54fc95a9de96249dddad02c9406c352c70ede4fd3f8eddd1655b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-x86_64-unknown-freebsd14.1.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "307b4b7bfcd37be27736d19a1fb0b95cb9865f32"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[libLLVM-build_log.download]]
    sha256 = "8f421e4cbfafa9a8972943e577eefdca0fe4928b31bd5dc936138703338b344d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-build_log-v17.0.7-aarch64-unknown-freebsd14.1.tar.gz"

[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3af2cd56b066eb2cb3b156a1735b6d4c4fa9f4b3"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "663c6673aa3b6eb20fdd09a35fe1adf006a17f8dfa6b441253e5fd78435518f8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "2162615a37b70337fe5862099e60d386e983f3a0"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "91ebf77f77328d4d7ba7f5446ece2feee3d2ec8c810a5d65e16aeba7c2831421"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a75d24802114eda6ad1430c33b7cdd94be2b09e3"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "3cf3869de224c49e3c4ef6f74de69d4bd4e42c4ed9e992fe4767b4c5c3211233"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97492fc79f7ad0c739acfe1b691ca3c71a49b05b"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "e1c0f4475fb4cbd66f64b8c80012e027985230e90cd494788177c888492e7c3e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "16d223143d8f5cbd0d9e3520c25619ec9234068a"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "78ca2bad577caa62dc16639b06ff665f8302c127994c30914803d1e409121a94"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2aea02c174008c19d49fb5492860a583cb79d1fc"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "1b8d1b28b3c18a9b61d3bb67e63091af4c1f05c3b788bdf3560fe6a84ee9b458"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "aad8ce70d38f485555042131f99687bf89e9a587"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "f8d297c316adbac06165bc9fae3036b5c8a10166f4786041cd78a7d53c846845"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "917a83bceae606d4113d986705f6dc37299409e9"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "4d16d4a81e93ca9d1bc2c4a19a68fbb387aa19902451d3e7c1bc33fa364f1564"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aba44ada7d0e107d9358ef43a9811d86f1c735c9"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "6d5b9f0d6afdf83e4343949d62e692af6a332f983cca1b96ca3e0c673ad3f826"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35c5c7cbc5a2176967305e9a2f100bc2c98b48a7"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "b65558045d3ffb690ce305137aee5b28a69cafa2a28da1d857d578d332573a92"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7c318b6127bb7066acd9e27f00ab83242c86e428"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "50413da399713f866dfc51e491a97df9994f919d0b46b78e895ddfc9132c2055"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "68fc6173e441601f6c0f2ac2074682ddedfadbe4"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "e3314732134e2ec68ae14a13735a62a38551a5812e2e89851f4b95a074dc9c43"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a5702cc311a7b358b95797a9aa5fd516d964d3c7"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[libLLVM-extract_log.download]]
    sha256 = "42ede7a478c39ab0b8602ccb3a40b2ea7beeb1ee70186a6522ba4f0a66022975"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-x86_64-apple-darwin20.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2be142a007d28c156c01f308235790fad3b742a8"
lazy = true
os = "macos"
os_version = "20.0.0"

    [[libLLVM-extract_log.download]]
    sha256 = "fb631191d34d635ac3a58e0b203e012dcbf6595059f023ad3c88567f7f38dfe1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-aarch64-apple-darwin20.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "636dccdb818b4099a96fe93f53ab48e3a2484e70"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[libLLVM-extract_log.download]]
    sha256 = "90cbae59c983845845a3d8a3e06d06578886ce75d850e177304d9f9d9ef15ede"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-x86_64-unknown-freebsd14.1.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "12053162175cbd06644b69ed685bb0679d36c1d5"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[libLLVM-extract_log.download]]
    sha256 = "f13f3572e661b5cc1c92387152854c23937013ff9e76e9048179ed4d78fb6e38"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7-GCCBootstrap-x86_64-linux-gnu/libLLVM-extract_log-v17.0.7-aarch64-unknown-freebsd14.1.tar.gz"
