[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "552c249f9016daf7274905631514b3df41454684"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2b56791880f53dd27252a2b4738ed29062762305988c2283bc2756aac856a138"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "5cc8e00997b8aecb730f8c7b40f8d317ac479913"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8a8b3bf2b15700451f77fa8bec2dcb9c99da89a3ad25cb4e248fe20e47140472"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "b874144d398402f53ff66b5eb5dd21f97015541d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "45fd5abdcd8b8fbae8528fb93e8f4c6546b5a9e644653353a30bd6ef186421ca"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da21c10406df38f52917935b788854a17d170fb3"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5a2c6fea7a284cbffb08c375b7cf2b59a9e0f1efef894396dc4efaccd1948fb1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
git-tree-sha1 = "a4831f2e5ea0e3f4668213f06491890501ef196f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9e8fb511574274ee06a13d5ce3a296d4483a6832a01493ad28416622aaf43c6f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "61f44ab16c1b10a75e6b8d471c4bb3482d8e8f5c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b1d5844650f4b69f46f827b73c09047c3714f1f73248e052af2347c7e27beea1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "88e1cb2547cf83d490c1082f3d9d1363eca66963"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "757e17a2688b1fe23e3fdbc65c0d4e0a2cedc0baed09eda3d8ab22a3fbae142b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "500be08e7c71b9b5cd760f74c232622f2e13d258"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d43d55e2dd5b5c8ef1066cc2850e11a49238058278c448dc33dcce360f0c360b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8bc09706e5cd660b13a71f873b051b5b95662ed4"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "cccbc8ca7e25f1f1307981b2ba0389785194db3c658843309972b65af28c3ac7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3829ed8dbfd32fa1653b7f364ddfdcefcd2029d5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a85a4ffb84aabeadb464a6272903ea65f01ceb3678c8c6acb7bc5334d3ff9f79"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "388490b93bc5f9453c55a61b81f90884ca1aa040"
os = "windows"

    [[libLLVM.download]]
    sha256 = "d1f08e84dde1f80dbf732c6653d9d6aabbb6b79be22524e18a5e3fa4cdc28308"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "ddd8e20f9e981005e1fb5dc323b79cf475ea5a56"
os = "windows"

    [[libLLVM.download]]
    sha256 = "4b2563ecf1c09caf7e649ac73294221a69f1aec2ac0320094855c232a32027f9"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "d968b75502df50e65a291fe1d54681c0910fdef9"
os = "macos"
os_version = "14"

    [[libLLVM.download]]
    sha256 = "a329c80af84b86a38f6f844c20e33a68770a437d6e32e82202282898f2f4d152"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "e224da3342a07a129f82505c191844263cba10f2"
os = "macos"
os_version = "20"

    [[libLLVM.download]]
    sha256 = "eabed6e1c7ebc973319b1e824bd52c6281aeafabc50bd58c58af5138238fd761"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-apple-darwin20.tar.gz"

[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "eacf4a5cde50d9a1c9241634c80b785faf30c16d"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "3d612b5d6ae0d9d911c3ba2c94ed34b6ba1261b276a7b4912f48778890f780b7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "b6ae2d95c5a34b8bb39b5a0f793996d3940d3dbe"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "2197dfea7b719f7057d0098b508f33325246f027aaa9b93f46170ad55fadfb32"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "d2983b5fa2776c29ee6bec1da3917f26099aa400"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "d51e78b8578c9cd3aee311a217a10a3fd0c07bf0941e169a283df9cb5bb6fe77"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7fc2b6527146d09969212d4bfdf11a683ef5242c"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "0b6455abea8662f1ae9520101b974bb66e4b0af98a21fac018f3b21b332a5bd7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "9404aa9e5b4b60cb68b6fbcc02607f48ddd32a7c"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "21cabf6446568edaaf8cfe16dd55a93edea554612efcc214a93df0c1b1b62db5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "ead536d7aa08a2f092bf641500806ec5d70f08da"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "9e5bbf463b60d94205846999e735b0845eebd839f7247f03c41120aab5228192"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "35f852bb604c42287c160a7a94ff4e8aeb7b6b07"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "b6609d33f9ecd4ac848bd3bddd3f48bb4a6e7bb95c4430051acebda1993e56ef"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "282ecee253f22a6c25529ff08caff22b3a74542f"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "75e5b4a47460d8a61a03c54f86e508f4483b17fdda9b3d5092adc3107dfb9798"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05b82bdcbba817c758401930550352242877d996"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "fd82142fb5508ab32f91e7ac63595f79cdbdd674ebfcffd984cb872b128eac02"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1728a366fafc5d0f9b97a19a0b9f537d3d2823a"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "589eea9d6df13fff2a3761dc35d7c85d88aa75474f9921b811880b41acc88db6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "ece705f7afeeff2b6a37340c8984086a46a161a5"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "b49e4a6ec1c724eb22d35a39ba0794be6df359c6ab49154dfd1016a685d30d79"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "8c6b661517c950b7a02ac2259312a14b95bb6bd2"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "5cc20a034fd46edc18becd3e7e14ea1b591e63dd38527817a81f1397cd7b944a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "78c44a09b35cc02d837192a36d7a6035deab3802"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-build_log.download]]
    sha256 = "596b6245b2dcde2ec367c900c5096ad224af089812efe13dac394cc3a9e2577b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "50fabc14d005f3ea6a6bec1a7da3d0f894bbac14"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-build_log.download]]
    sha256 = "0e1337d4f2dfcf9c2ddc1b94fc27b431acf1a3e92d71f04e7f1cea93986eaf6b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-apple-darwin20.tar.gz"

[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9257c59049e5f52391931c9fd163bf75c6ea2eb8"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "ee5fcfcfac6f7db74b56c8fe3857a189a5cd1baad9e5670299149fd5e92d9528"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "4c6900db1a58c32ee8b3d8e74c7965fc46dfa3b9"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "807a053a85e84b078469375d1faa5dddab766f9f8bd36325e0cdac2c0fe8b2d8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a9f5d760d8e6a695da4e1934f7111c2cc0d30815"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "7f0c3e9ce04d506db2cb112d01703d85d4798d39bcf59774a3e2e1b60244b0e3"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0396946503c27513f68dfd308a579b5725544770"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "87cf21f0b5b56a8f6b21020223e8511c8194b5f2a1e40e0619bf3bcc7cd390bf"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "00011cc3c057309a6236a03a8aaa0407a4e6224f"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "7d2add3d84b30696de75a900df9fd1e472933a2b5b18dec50a0cc53b05f51502"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a97939187f4347a1e3c0ce145f3b95081d1166bb"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "fae287fa7d2ea205f7a618164b09208bcfa8101bfb0b9f38f8b0f8245a1b6ab4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "d592980c41aa8f10da9e5956beed4a41a5bb3b2a"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "f9b9dacd4deec67b5a037189b7b35bae5c34d3654a742e57ce182be3f8dd7e1a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "0275fa545e2119e9cf28f528c1823dfa20d71ce5"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "3e455098fe3c34794dd84a37719d202fda91356406ff35e118f2131a5a9d496f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20bd486d7a2670de4f280a44cf4146c136df765d"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "b83544a79e430c3de50f18e4c2b24be8550fc418eda63327a7244d2e4a98c13e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e62e4161f10e5c2cd1ff6025d864c21abb56fd79"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "93a2297cf196920f245eab4c9afec2a6df0a39adc724e979a8f28a427102c420"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f0541c0af8ea8c5776d4886dd221bcc7dc45013f"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "b445496b9d3574c6d1474c39652e5eb8014f0a58c1881d56de0c9b90f52d413e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "499d3b4508808eb43c26a6997d1d4ce3bf0dfc5b"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "4f6581aec782555a29e171a0504c6b1e7ac099ceeb20fb6908896032ba8c04f2"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "461f8200eb8d633b36058465595c3d80536fb1f2"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-extract_log.download]]
    sha256 = "53522a4000260aec9f151cda771111a36bb5c8c0e4ff8b0873b14d2f5a8272ca"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aed3c99bd1c34ccaa471c391a3ba021f4d57b77b"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-extract_log.download]]
    sha256 = "a7d13b4035088052daee060842b8c9bfdb4fc5b70b1e1d714e8fb06f271802e9"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-apple-darwin20.tar.gz"
