[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "5670b857848ee4bd120cf4e8886dbab575ca7b99"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "90b3aadd556bfcf6fffbd77f466226d75b24c7da132b7644a5bd1f51774998e6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "2ce90033cb04fe6974cc8bcfc6cee4e93222fba0"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c2925a79458b628bd3965a4bc7401a1fa289e6a9f44fee2f2c0051e4c549c5b2"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "75bc2dc95815059a66994ead1965dd73e4df222f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "119330a282f61566972d40c62f04ca01849b62b0013d3701b55fa019469fa730"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e9eb98a7f3c4596554c1cd1573c28435fce8236"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6894abbcae4d85145400229ac1faf68263767149350245de308b0432122965c3"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
git-tree-sha1 = "4b3299713dc7189994cbd2941d196c7294dda831"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9c5d5207a02f9e9edc0059938a789578278179f6261d3ac1ef4daaa49c7943f6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "9882f436bd3de83cb2322be32bd1b1973e4e80f1"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8fd2fe55b93517dfe987e64d3a8203a71e74091378ec5f74db1b29d34082add5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "b7b1d571ff6d8ee3a0637da3270b0c14c3848a76"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2e9f527e003996f0ad31f59828184f4482603b656c725652ab753678030d1a1c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "00f4ced7d9c82b4cb04a7540cc07f49c725424ba"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ac590216ff277dd435c391c38767e9218da9a8102ef9cd0c2ffe4653bd9399d2"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d32f419adcb6aef5fcc90036ad1af336c67c65a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6c4a50ae646341f1751d7baf2edb1ac497d625162b4e73812a685ab943a51244"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c6d9b8adb51d503fecc63af2f4bfb6ee123057f7"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "31b014a8bfff45fd27f23130ace552bb5b9875effff825d79ffc3bbe06d1418e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "087eade6f0f6d567b66960eed370644f129992ab"
os = "windows"

    [[libLLVM.download]]
    sha256 = "dc73c95e4387d4007a574c7d614d069ed9e84ab948e896674f19804dc2ad5e5c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "f05309d0f430426bfe29f1e5bb88df9a5aa2d369"
os = "windows"

    [[libLLVM.download]]
    sha256 = "904da80a310973aed26d9261f59a5650c1685507f811a4651dd019be81dbfd2c"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-w64-mingw32.tar.gz"

[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "b1c522a203307f1eb48c921fc4e0422c03acca2a"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "5fc58611396037d29b50b76d6b2c63669efbed96cb72403e8372c8170ab4a50b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "2ebbb8aeae777978a2bc0352dec6f3f35c0eb852"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "d4306b8b6694a55d41f3e599963d8fd11270da7f75c74308571e9fd9518b7dba"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "d8b97f75c01b90512796f092789f83e7c64b21e7"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "3282c88dd482001e826909d28868d648ccc0e1b46dd67c7bf2eb3ab81486ee0e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c97cd6ac1ac6a1ac47da5441456d5a86d98883bb"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "b85b4a31f9c9b2690e926f0c091a1919c494d8118a5a6d0968a633cd2358c37d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "f76a028cda3e44393b2b4645e236305bd4ca1d30"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "74fcbb361ab7750ec48f3c264f31d1f5d73234991a7bf377d9baa27c7fe42b2f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "bf8172b149551d194ccb74e10b230560d5d8c005"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "b611dadb0cea690fd1924b01a105ba454c45e267b206babd2a953582dff5b85d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "357e285c92a20173ef4b0469059f4517afb951bc"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "12f8b943107e5221af42d712181a2ae9997d2a091d9ad39ab2a839334a15dc1d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "e95e054835ad383fd9902102b6f04443554c2718"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "9557c8b0deb2919e89fc06bd035e0f40ea0efa1a11ab2f7ad97de9fe68146998"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bbe65c86f220ca53663f5c900c763800aad8c28"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "5e58eb287b4e71da9e701a97de9546da11cde5b598307f278246c36acd16b8e8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6afc7996ea0b79195bf53803940403954467eb90"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "6833d963fd64f11b5fd688ce44768e6093079fbf787a30c838a909a23e42dbd1"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "4c9286d278acb2d69b46bfc9d9133ee6afb8889c"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "2731c7d692efe51253f280ca83d26f918acee97303fdfd3644f6ad411e2e72e0"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "7434232d81bd5253a63c79a4a413eb139c876aa7"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "99581699d708ec11f0a8563a4281bc4c12ca5747481ecf1d1bf6b47686a68e75"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-w64-mingw32.tar.gz"

[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b8dd1765fc1250ab41ff1ad3fa234cd63b629fde"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "4773fd69b27dbac88ef91c6e40579f8ff3332aeacc4fee43110ced0281d0630d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "ba2007865b465c874f0a5d62c0c2f528cf9aa1e7"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "40a62ec6f1f9603f810cbf8585e76750cc291290531ccda10871704fe48d2029"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a34db2cc52141647811ee1383c87f3f66b7d9972"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "c726dd52707548c2c1d3e49897909c47048aee7923b1a55a76c15b1d9c640496"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2272c0abd7321abc28a12d471312a6ac9c6d967"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "267e1424865e096d9fc23ab676f0005c31f4d5edeacd126a7a82d70e9bf7351f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "4dc5997e82bfec3231635672ae55a09665e0fe92"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "ee640b3a3c7ef14a31e4197a9036ff176923ca6ed48a0e08cbe1ae27d534671b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2903ee0a934212d3232b815a048677b7b2fad54d"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "33ac0d8f3b816f5e7affa44a0cad94ee44b0bb4854334f7576083abdd09a743a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "5de80f1697a25dbabe3bae82ea3dc91d3d56b00b"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "0565d1afeb5b2c3bef4ddf031ee765691117b4006c43faee5ffd4e512d27c07d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e4310f7c1bdd2cb2a70af6f3a06124f402e4d470"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "bc84471063b4dab70230c54cc24cf219496f8097901b4e5ce21d6e00963cafc5"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56b164e3e219f372a32590737ef84a938aa0e2cd"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "c8c644440b54b7a3728a03d6d0b80ea0cb1ccf22a0256457395fad96ee0ec65b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df77b85b093e231f26cfc14473f9f400c80e935e"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "6c7876462ad858a7ed6764303b6b0c0c42fcf8dc4a10bd919a3cad6dfb329679"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8a5af673693272f64953535c069ec9537e9b64a6"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "c45c712c060e8db88352eac95f1a4492d401d3ed490b6d913fefaf83b489dbde"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "47d410a649bf6dac201f3557b621bc616be99a9a"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "42fb32320f67dc68779c6ee00c5eccfff6623ac743ac35c1b8fb3a0e7dba1391"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-w64-mingw32.tar.gz"
