[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "552c249f9016daf7274905631514b3df41454684"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "57301059f8536df68b0377dd3011460f4e79defe1abda683bb14e6c9e1bab219"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "5cc8e00997b8aecb730f8c7b40f8d317ac479913"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e337a14aa932f4bf12b5e7b5f19dd8ac4aa35ee256b81ed0e86e4b23db603a56"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "b874144d398402f53ff66b5eb5dd21f97015541d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "000e5667440efb2274398d9acdf0fdc2ba0368df2818a34095927b8ed57fea0a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da21c10406df38f52917935b788854a17d170fb3"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "639d4e268866f2f31c44ad63b46152272534d85b49e07b5e421cb7c5b30d2397"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
git-tree-sha1 = "a4831f2e5ea0e3f4668213f06491890501ef196f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ce4795ca3ba50336b40311d4bfc0c628441c6234e195a1206e39331a63ba3026"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "61f44ab16c1b10a75e6b8d471c4bb3482d8e8f5c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f09ddf89efe1f511afa0187321053e06bf0d6efc780e5567c11cb61272e76b7e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "88e1cb2547cf83d490c1082f3d9d1363eca66963"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ef0c36d4a5a0ea3225828ee8bc651d10d54922373487876006f5495e5e635b64"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "500be08e7c71b9b5cd760f74c232622f2e13d258"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "40d1d910d5b71bf3702c1cfe17e904169801e24d204f1d96c1875336ce7ad4d8"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8bc09706e5cd660b13a71f873b051b5b95662ed4"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "59c8f4e641bf2d3573b4abe33b160e7592a904e98c24f93e6c6484d95b3b7b67"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3829ed8dbfd32fa1653b7f364ddfdcefcd2029d5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "fc4ea9f2a807014be69b54c0d54a3b8a93e90fde05b44e6726a0b64af6a01755"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "388490b93bc5f9453c55a61b81f90884ca1aa040"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ed8fb5b0ebea7035d6bc78104158db4f5ae27993a5ed5da894d609706ac875b7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "i686"
git-tree-sha1 = "ddd8e20f9e981005e1fb5dc323b79cf475ea5a56"
os = "windows"

    [[libLLVM.download]]
    sha256 = "a3b34bbdcde99c6abeea029bcbb7e134270ac8e26e2a2b755baaa3cb6e5ebc52"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "d968b75502df50e65a291fe1d54681c0910fdef9"
os = "macos"
os_version = "14"

    [[libLLVM.download]]
    sha256 = "02708a0def31723db97520168b2210f9282d29a446464c9e5fbf7fa9777502a6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "e224da3342a07a129f82505c191844263cba10f2"
os = "macos"
os_version = "20"

    [[libLLVM.download]]
    sha256 = "7a6ac9eeb8eb137a8c4536976d316b342e32c35752a51abd703c520554cb0237"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-v17.0.7-aarch64-apple-darwin20.tar.gz"

[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "413b5cb9130bb06768d0d4d6286b8a2ccfe67305"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "69e0038810a6b11f409911434115b82092c5cc985fd0f556356af9458ba3ba9d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "c1e19e73df216e49b011e56d9d7431fa6c0b7dde"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "4c2be92ae4bc4628f9955e8c7d0de7ebf944d7f8fcd0b76c3d4081dd2a98be71"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "9ee6ff551866a94f372c3d25c1e920b0aefc2f86"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "7f769f244d59f58f6c5f7ba56b6712df542561881b5111bad1723a699b55c880"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb8c6d6057ef9c2a9f72eaf73c2bb7a7f65b7ed1"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "d4bd05cacc8f7dc09bd2613ae83f8474e91536c82ce7abf111ed97e24cccb65a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "76c28d36df0f7364159ac564cae84fa42751fd51"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "36315fb76a31e158ecc6c263c554568e342c43481a70a005b1d9a08b792d3b20"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "4a09d005ac6a94e0199dfc36e67df213cf7ac650"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "c6b4a6964e0e0a0b195f1ace1a0bb0c55588690da218cd7e432eecc78e10bcb7"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "6a2c3bff6a78d3b0be6cb4587a31e2e24bd6f46b"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "3d28f88a9c4034e29931d7e9a2a31a50cbdf18eacadcce610c4db249d0e6e0d4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "b8131396cee7ce352b3532a53c286e7e13a07390"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "91108cc91d21e78c4c8380a29f092fdb26f84004c8294dce419c6abf0f09df34"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb6eb8247177434466a6d4393d228cc07fb25ea5"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "620b296b4d25902380285bafec1f8832d188497a0d75324bda2dae8ab690b1e6"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51da7bded5bd33415ebf5826f26d91f7a0af1dc9"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-build_log.download]]
    sha256 = "4863c956c3edb79fd8190e60d7fb1ad9446c88d82987899b4594c9f5a0989e0d"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "ff6f641b99470254bcfcbfc46afffcf420f55806"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "240982e11832a34b954302be22d2a5572342946cad76f25a59934fd91c8e5a46"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "i686"
git-tree-sha1 = "f3f2a2ae806a8e830997fe2df374974a2b3be336"
lazy = true
os = "windows"

    [[libLLVM-build_log.download]]
    sha256 = "d902784f48a3caa92ab4faf1a688eb13ec257929bbca95cdbc50d6556dcdc3de"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "a9f6a588f82c37f04cbbd699eae39fab7a44c73b"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-build_log.download]]
    sha256 = "0473344fae9357df72546c5d90cc314477d7c5013ece674475799ebf63f1c03e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "21a9505cdfb421350a98335cc9fc0aeecd0f49a9"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-build_log.download]]
    sha256 = "db8f093e878672a14ebf11d8be91deb6558337809a01c9bdc9673a9afb1dde6a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-build_log-v17.0.7-aarch64-apple-darwin20.tar.gz"

[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d3837723739da0cb1a9b3e53807219bda82f49be"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "fb85cb0e4e5b841c5fb94ec23c3ff412d78d3b23ccd0fbf5ec7294e6426d092b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "b9813fec07830712a8db9cab11509488d6f1a9be"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "d27a0b37b3a6789baaa7d49f12ffb433afdf897df57dfea918092777dbf10a09"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "1c5035e332313844a10fc9ccfdf1b1474701107f"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "a0a6a7639b1a749ebf1e85b2e3f9783219794728f5ffe1e4d0caf7f77ce7666f"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a22460ced56044415a8f655429dcfef9e24bc94a"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "0b80295f5623a26408d631904d63fed3016ffc0bb4f133ead9a3c2458adf5142"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-gnueabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "d00c112d87d4c04a0a015a3fc35586c10e7ca3e0"
lazy = true
libc = "glibc"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "fb724a94ebdf26aa0729a0dca605f77f351660f565705b839313c8d1fab3eb98"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-powerpc64le-linux-gnu.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a5ce3104747af024a9379e837e0ad4cebe8cb215"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "d5dfa539deeab070d954038b7788c97849691568a4ab8109f5adf97bafb64563"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "a3e71c42bfd1ab60b041cf94acb9d7344b265895"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "99661c40c668a7f7ee14f2fcd422ecd0ffefc684d777d573b5dee3c48a973b65"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a90c3db17024662f421670a5575ada71079b1b31"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "de4f6c8827ff320530c36f975eadcba4f419baba12db3ce59c7e170f634ba312"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-linux-musl.tar.gz"
[[libLLVM-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b5d4810a42f00691fc603126f6c2949c9d4ea89"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "60ef0d3e168b49cbbcb41e551308ccac486d80a8042e8659d52819a488f2871b"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv6l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d201c0de2e04b0a04dd75062680482864942eb5"
lazy = true
libc = "musl"
os = "linux"

    [[libLLVM-extract_log.download]]
    sha256 = "feff5769e1de5f9d81f3dbae7b6492e83a9d30e76f8a3f8ffa8de4a6351ed63a"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-armv7l-linux-musleabihf.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b91098a2f1c557a54784b56a6bc7752af444c870"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "29d0900ffe2dd43dd56e7e83b05015fea292ea7e4946e660b61dd2a2e32cf5b4"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "i686"
git-tree-sha1 = "be9675fbef9dc0ec78f48cfb439e7c0742964250"
lazy = true
os = "windows"

    [[libLLVM-extract_log.download]]
    sha256 = "65a072b65276263293175173386eaecca67743e058f53fe9d1bb83d75230c82e"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-i686-w64-mingw32.tar.gz"
[[libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d6a1024060e05573824e41f1992795861e0a3e06"
lazy = true
os = "macos"
os_version = "14"

    [[libLLVM-extract_log.download]]
    sha256 = "c545d33c5c5e4564627c5856966f28c7f3297405dda6a4b5e8b93d8a6c0d4abd"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-x86_64-apple-darwin14.tar.gz"
[[libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b41524f44a55ea3e1a8d17857ee3f513600c2df7"
lazy = true
os = "macos"
os_version = "20"

    [[libLLVM-extract_log.download]]
    sha256 = "c816a4117028811dde04a861f886138172d08c6e89d612167c254eccf7a18882"
    url = "https://github.com/staticfloat/libLLVM_jll.jl/releases/download/v17.0.7/libLLVM-extract_log-v17.0.7-aarch64-apple-darwin20.tar.gz"
